### ISSUE TITLE
working and restarts

### ISSUE THREAD

**Issue by aldomex78** [TheComputerGenie/KMD-solo-mining#14]
it works for a couple of minutes then restarts and shows the next message:

node:buffer:323
  throw new ERR_INVALID_ARG_TYPE(
  ^

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be of type string or an instance of Buffer, ArrayBuffer, or Array or an Array-like Object. Received undefined
    at Function.from (node:buffer:323:9)
    at scriptCompileP2PK (/home/aldoserv/KMD-solo-mining/lib/stratum/transactions.js:26:12)
    at exports.createGeneration (/home/aldoserv/KMD-solo-mining/lib/stratum/transactions.js:97:25)
    at new BlockTemplate (/home/aldoserv/KMD-solo-mining/lib/stratum/blockTemplate.js:35:35)
    at JobManager.processTemplate (/home/aldoserv/KMD-solo-mining/lib/stratum/jobManager.js:79:32)
    at /home/aldoserv/KMD-solo-mining/lib/stratum/pool.js:418:66
    at itemFinished (/home/aldoserv/KMD-solo-mining/lib/stratum/daemon.js:117:36)
    at /home/aldoserv/KMD-solo-mining/lib/stratum/daemon.js:124:88
    at parseJson (/home/aldoserv/KMD-solo-mining/lib/stratum/daemon.js:69:17)
    at IncomingMessage.<anonymous> (/home/aldoserv/KMD-solo-mining/lib/stratum/daemon.js:75:41) {
  code: 'ERR_INVALID_ARG_TYPE'
}
Node.js v21.5.0
[Pool][Thread 0][12/26 20:35:53] Fork 0 died, spawning replacement worker...

**Comment by TheComputerGenie** [comment]
For chains that pay to a pubkey, you must add your pubkey to the config.

**Comment by aldomex78** [comment]
Hello, always used address, not pubkey, mining MCL

**Comment by TheComputerGenie** [comment]
> always used address, not pubkey
Yes, this version uses whichever the block template uses. It was an addition based on a 2019 NN test and I never thought to document it. Sorry about that.

**Comment by aldomex78** [comment]
Hello again, a question about mining marmara credit loops MCL, do you know why using this repository only can find unactivated coins, and if an activated block is found it does´t show in my wallet. 
This didn´t happen using knomp, but it seems owner won´t fix it soon. Sorry and thank you

**Comment by TheComputerGenie** [comment]
@aldomex78 
> Hello again, a question about mining marmara credit loops MCL, do you know why using this repository only can find unactivated coins, and if an activated block is found it does´t show in my wallet. This didn´t happen using knomp, but it seems owner won´t fix it soon. Sorry and thank you

I have worked out a solution for MCL, but it's not included in this pool.
In order to mine both odd and even blocks in MCL, the pool has to use differing template and transaction types in order to accomplish using of the CC addresses and signatures. This requires some specific coding and would confuse certain development aspects of this repo.
It's possible, but not highly likely,  that I'll create a different repo for MCL; however, at this time, no one (including myself) is willing to publicize the needed changes.

**Comment by aldomex78** [comment]
hello ComputerGenie I won't like to bother you, but you are one of the contributors of Knomp, and I just tried the Jockeyvb's version, it seems to work but I'm stuck in this message when starting the pool, and I was wondering if you could lend me a hand:

TypeError [ERR_INVALID_ARG_TYPE]: The first argument must be one of type string, Buffer, ArrayBuffer, Array, or Array-like Object. Received type undefined
knomp    |     at Function.from (buffer.js:207:11)
knomp    |     at OutputPoolInfo (/home/knomp/knomp/node_modules/stratum-pool/lib/pool.js:107:26)
knomp    |     at /home/knomp/knomp/node_modules/stratum-pool/lib/pool.js:56:29
knomp    |     at StratumServer.<anonymous> (/home/knomp/knomp/node_modules/stratum-pool/lib/pool.js:509:13)
knomp    |     at StratumServer.emit (events.js:198:13)
knomp    |     at Server.<anonymous> (/home/knomp/knomp/node_modules/stratum-pool/lib/stratum.js:467:27)
knomp    |     at Object.onceWrapper (events.js:286:20)
knomp    |     at Server.emit (events.js:203:15)
knomp    |     at emitListeningNT (net.js:1314:10)
knomp    |     at process._tickCallback (internal/process/next_tick.js:63:19)
knomp    | 2024-03-28 00:59:10 [Master]	[PoolSpawner] Fork 0 died, spawning replacement worker...

As I remember I included the pubkey, but it didn't work this time
