### ISSUE TITLE
var dateFormat = require("dateformat");

### ISSUE THREAD

**Issue by mkphaber** [TheComputerGenie/KMD-solo-mining#24]
Hello
When I do npm start

I'm getting an error like this. Can you please help? Everything seems normal. Is there something I'm missing?

root@solo:~/KMD-solo-mining# npm start

> kmd-solomining@0.2.0 start
> node --no-deprecation init.js

/root/KMD-solo-mining/lib/stratum/transactions.js:5
var dateFormat = require("dateformat");
                 ^

Error [ERR_REQUIRE_ESM]: require() of ES Module /root/KMD-solo-mining/node_modules/dateformat/lib/dateformat.js from /root/KMD-solo-mining/lib/stratum/transactions.js not supported.
Instead change the require of dateformat.js in /root/KMD-solo-mining/lib/stratum/transactions.js to a dynamic import() which is available in all CommonJS modules.
    at Object.<anonymous> (/root/KMD-solo-mining/lib/stratum/transactions.js:5:18) {
  code: 'ERR_REQUIRE_ESM'
}

Node.js v21.5.0
root@solo:~/KMD-solo-mining#

**Comment by aldomex78** [comment]
Got the same error when update

**Comment by TheComputerGenie** [comment]
a)
[you need to update](https://github.com/TheComputerGenie/KMD-solo-mining#update-including-any-module-changes-)
due to [dc0f2bf](https://github.com/TheComputerGenie/KMD-solo-mining/commit/dc0f2bf7c8b812b1946485761d2d3156560d7998)

b) **never** run apps as root unless they _need_ to be ran as root

**Comment by TheComputerGenie** [comment]
Also, I will look into if it's an import vs require issue of the newer versions

**Comment by TheComputerGenie** [comment]
This is everything wrong with node projects and using npm.
We don't even use this package in the solo version. I erred in even adding it; sorry.
