### ISSUE TITLE
Running but not accepting shares z9

### ISSUE THREAD

**Issue by 49handyman** [TheComputerGenie/KMD-solo-mining#4]
been testing and installed easily but not accepted shares from authorized miner.

also got error, i think on redis server

CLI: CLI listening on port 17118
[Init][Thread 0][02/14 20:41:48] Spawned proxy on 1 threads(s)
[Website][Thread 0][02/14 20:41:48] Example app listening at http://0.0.0.0:8088
[Blocks][Thread 0][02/14 20:41:48] Current block would pay: 3.00262746
[PoolWorker][Thread 0][02/14 20:41:48] Stratum Pool Server Started for Komodo [KMD]
                                                Network Connected:      Mainnet
                                                Current Connect Peers:  16
                                                Network Hash Rate:      99.72 MH
                                                Current Block Height:   2265451
                                                Stratum Port(s):        3850, 3851
                                                Current Block Diff:     407555545.0011091
                                                Network Difficulty:     411209501.6595058
                                                Block polling every:    5 seconds
[PoolWorker][Thread 0][02/14 20:41:48] p2p connection successful
[PoolWorker][Thread 0][02/14 20:42:48] Authorized RQHibKZzKSzkVTHqgheFm7m7mJ7qbXsLFV.z9-50x131:x@::ffff:136.32.180.78
[PoolWorker][Thread 0][02/14 20:42:48] Unknown stratum method from RQHibKZzKSzkVTHqgheFm7m7mJ7qbXsLFV.z9-50x131 [::ffff:136.32.180.78]: mining.multi_version
[PoolWorker][Thread 0][02/14 20:42:58] No new blocks for 70 seconds - updating transactions & rebroadcasting work
[Blocks][Thread 0][02/14 20:42:58] Current block would pay: 3.00536218
[PoolWorker][Thread 0][02/14 20:44:08] Block notification via p2p -->> Block: 2265451
[Blocks][Thread 0][02/14 20:44:08] Current block would pay: 3.0065269
[PoolWorker][Thread 0][02/14 20:44:31] Block notification via p2p -->> Block: 2265452
wait loop data: {"error":{"code":-1,"message":"CreateNewBlock(): create block failed"},"response":null,"instance":{"host":"127.0.0.1","port":8770,"user":"entrust","password":"entrust","index":0}}
[Blocks][Thread 0][02/14 20:44:34] Current block would pay: 3
[PoolWorker][Thread 0][02/14 20:44:34] Block notification via RPC polling
[PoolWorker][Thread 0][02/14 20:45:44] No new blocks for 70 seconds - updating transactions & rebroadcasting work
[Blocks][Thread 0][02/14 20:45:44] Current block would pay: 3.00181044
[PoolWorker][Thread 0][02/14 20:46:54] No new blocks for 70 seconds - updating transactions & rebroadcasting work
[Blocks][Thread 0][02/14 20:46:54] Current block would pay: 3.00375574
[PoolWorker][Thread 0][02/14 20:48:04] No new blocks for 70 seconds - updating transactions & rebroadcasting work
[Blocks][Thread 0][02/14 20:48:04] Current block would pay: 3.00456758
[PoolWorker][Thread 0][02/14 20:48:55] Block notification via p2p -->> Block: 2265453
[Blocks][Thread 0][02/14 20:48:55] Current block would pay: 3
[PoolWorker][Thread 0][02/14 20:50:05] No new blocks for 70 seconds - updating transactions & rebroadcasting work
[Blocks][Thread 0][02/14 20:50:05] Current block would pay: 3.000624
[PoolWorker][Thread 0][02/14 20:50:14] Socket disconnected RQHibKZzKSzkVTHqgheFm7m7mJ7qbXsLFV.z9-50x131 [::ffff:136.32.180.78]
[PoolWorker][Thread 0][02/14 20:50:47] Authorized RQHibKZzKSzkVTHqgheFm7m7mJ7qbXsLFV.z9-50x131:x@::ffff:136.32.180.78
[PoolWorker][Thread 0][02/14 20:50:47] Unknown stratum method from RQHibKZzKSzkVTHqgheFm7m7mJ7qbXsLFV.z9-50x131 [::ffff:136.32.180.78]: mining.multi_version
[PoolWorker][Thread 0][02/14 20:51:15] No new blocks for 70 seconds - updating transactions & rebroadcasting work
[Blocks][Thread 0][02/14 20:51:15] Current block would pay: 3.00465397
[PoolWorker][Thread 0][02/14 20:52:25] No new blocks for 70 seconds - updating transactions & rebroadcasting work
[Blocks][Thread 0][02/14 20:52:25] Current block would pay: 3.00527797
[PoolWorker][Thread 0][02/14 20:52:35] Block notification via p2p -->> Block: 2265454
[Blocks][Thread 0][02/14 20:52:35] Current block would pay: 3.00565241

**Comment by TheComputerGenie** [comment]
nothing show indicates any shares not accepted (and only shares that find a block actually matter)
also, it doesn't use redis, so not sure how you'd get a redis error without using redis
